### ISSUE TITLE
Organizando a apresentação Pitch Deck e MVP, com todos os resultados obtidos e funcionais.

### ISSUE THREAD

**Issue by Ronynetwork** [Ronynetwork/AVSAC#10]
Nesta issue realizada a organização dos dados obtidos nas etapas anteriores e certificação das funcionalidades que foram inseridas do código, afim de apresentar os resultados em forma de slide.

**Comment by 1Sayza** [comment]
A apresentação seguiu modificações com base na orientação de Felipe, que foi eleito o nosso orientador do projeto.

**Comment by 1Sayza** [comment]
A seguir, será apresentado alguns anexos da apresentação que ocorrerá no dia 12/09. Mostrando todas as atividades realizadas com o intuito de apresentar a proposta de uma infraestrutura que tenha automatização aplicada a verificar segurança ao código.

**Comment by 1Sayza** [comment]
A primeira mudança solicitada foi referente a introdução, que o correto seria tópicos em vez de um texto.


![nova1](https://github.com/user-attachments/assets/9e13c3f8-1e14-4bbe-992f-d116a81ff216)

**Comment by 1Sayza** [comment]
Lendo as instruções para apresentação, se conclui que será necessário apresentar o canvas novamente, o modelo de negócio que preparamos para apresentar da nossa empresa AVAC.

![nova3](https://github.com/user-attachments/assets/9305b07e-9a38-4613-9a1d-d792ba754a93)

**Comment by 1Sayza** [comment]
Temos que apresentar um problema, o porque escolhemos uma solução de serviço para vender as outras empresas. Ou seja, o que resolvemos nessa atualidade.


![nova2](https://github.com/user-attachments/assets/c811a10f-b792-43aa-81e7-0c0bc82b2505)

**Comment by 1Sayza** [comment]
Temos que apresentar também as tecnologias que utilizamos para integrar a solução ao serviço. 

![nova5](https://github.com/user-attachments/assets/a9f9cb2e-69b9-4bb3-8a78-43e87f27912e)

**Comment by 1Sayza** [comment]
Apresentar todas as sprint planejadas para cada integrante do grupo, uma forma de mostrar que cada pessoa do grupo, teve o seu papel importante para chegar até a solução do problema apresentado no início da proposta.

![nova6](https://github.com/user-attachments/assets/09f725e5-79a2-44bf-929f-cf9d02dcf45a)

**Comment by 1Sayza** [comment]
O anexo logo abaixo é um resumo da apresentação sendo finalizada. 

Segue o link para leitura da apresentação:

https://www.canva.com/design/DAGO5-QrGPU/_08Z9CB9mo7cy91mqBHjZA/edit?utm_content=DAGO5-QrGPU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

![concluido](https://github.com/user-attachments/assets/8a80dca6-548d-4be2-805d-7bebedf68449)

**Comment by 1Sayza** [comment]
A apresentação poderá ainda sofrer mudança, caso ocorra do orientador solicitar algum ajuste.
