### ISSUE TITLE
Implementando o Webhooks do Jenkins ao Github e SonarQube

### ISSUE THREAD

**Issue by 1Sayza** [Ronynetwork/AVSAC#12]
Tarefa de tentar implementar Webhooks do jebnkins na integração com o Github.

**Comment by Ronynetwork** [comment]
Para uma melhor integração entre as tecnologias, iremos utilizar dentro do nosso ambiente e de nosso projeto algumas webhooks para automatizar a geração de builds e análise de codigo.

**Comment by Ronynetwork** [comment]
Escolhi utilizar o Ngrok para a questão de gerenciamento da url e direcionamento de tráfego até meu servidor jenkins entre os serviços. Para a inicialização do ngrok no servidor que esta seu orquestrador, segue os passos:

Fazemos a primeira configuração e instalação da tecnologia na máquina:

![image](https://github.com/user-attachments/assets/22ae57ed-20b1-4a54-b056-6489bcfde4bd)

**Comment by Ronynetwork** [comment]
Geramos um token de autenticação par ao ngrok conseguir realizar suas atividades dentro das tecnologias:

![image](https://github.com/user-attachments/assets/3a926d03-76c8-4cec-ab2d-b6a15d8b9827)

**Comment by Ronynetwork** [comment]
Finalmente definimos qual endereço de url iremos utilizar para mascarar e gerar um webhook de acesso para coletar as atualizações de estado produzidas pela API:

![image](https://github.com/user-attachments/assets/c56e00ca-7c87-4d2e-a267-9292058bbf2e)

**Comment by Ronynetwork** [comment]
Com a configuração do ngrok feita e funcional, utilizamos a url gerada pela aplicação para realizar o cadastro nas demais aplicações: 

![image](https://github.com/user-attachments/assets/7f0a29a2-185d-49c8-b1ef-7c6ea2acc184)

**Comment by Ronynetwork** [comment]
Dentro do Jenkins precisamos configurar para que ele aceite o Github hook trigger e assim consiga monitorar quando acontecer uma alteração no repositório, deve ser configurado pelo caminho (Pagina do job) > Configuração  e selecionar a caixa abaixo:

![image](https://github.com/user-attachments/assets/3fa32e58-d74d-4a6c-b85c-ea04d7178b31)

**Comment by Ronynetwork** [comment]
No Github precisamos adicionar a url que foi concedida pelo ngrok e adicionar o sufixo de /github-webhook/ para o funcionamento ideal:

esta configurado para nao ter autenticação e ser ativado apenas em push
![image](https://github.com/user-attachments/assets/113462f9-3d81-4174-8f0b-1bc452868a0c)


Depois de realizar o push com a webhook configurada corretamente, a seguinte mensagem deve aparecer:
![image](https://github.com/user-attachments/assets/85fc234f-0264-4e38-93cb-d9c25e4c0014)

**Comment by Ronynetwork** [comment]
Dentro da pipeline ja conseguimos verificar o retorno da interação com o Github hook log:

![image](https://github.com/user-attachments/assets/d5b9ada6-fd89-4a1d-86f4-f99091d5b571)

**Comment by Ronynetwork** [comment]
No sonarqube vamos utilizar webhook para retornar o status da verificação do quality gates que define quando a pipeline vai realizar o build para produção ou não:

![image](https://github.com/user-attachments/assets/376c8eaf-1bc3-4c71-a838-ecc95bff5c97)

Pode-se perceber que a unica diferença se da no sufixo após a url do ngrok para fins de diferenciação do próprio ngrok e das aplicações.

**Comment by Ronynetwork** [comment]
Por fim, temos o retorno do Quality Gates com essa webhook configurada dentro do projeto do SonarQube:

![image](https://github.com/user-attachments/assets/405f7f21-81de-424a-ab1d-bfb275435f32)
