### ISSUE TITLE
Configuração do Jenkins

### ISSUE THREAD

**Issue by Ronynetwork** [Ronynetwork/AVSAC#2]
Nesta issue será realizada toda configuração inicial do jenkins pela colaboradora Sara Maria, onde deve mostrar a tela inicial da tecnologia funcionando e primeiras configurações.

**Comment by 1Sayza** [comment]
Utilizado o sistema operacional ubuntu linux na versão 22.04 para a instalação e configuração do serviço do Jenkins. 

Os scripts utilizados com base na documentação do Jenkins. Segue o link de referência da documentação:https://www.jenkins.io/doc/book/installing/linux/

Os scripts utilizados foram durante a instalação 

sudo apt update
sudo apt install fontconfig openjdk-17-jre
java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8+7-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.8+7-Debian-1deb12u1, mixed mode, sharing)

Esse primeiro script em acordo com a documentação, é preciso instalar o Java a partir dessa versão. 

Logo em seguida, utilizei o script que instala o pacote do jenkins 

sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
  https://pkg.jenkins.io/debian/jenkins.io-2023.key
echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
  https://pkg.jenkins.io/debian binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update
sudo apt-get install jenkins

**Comment by 1Sayza** [comment]
Os anexos tirado print durante a instalação do Jenkins
![Imagem1](https://github.com/user-attachments/assets/7e247a4a-817f-44d1-acf7-5cfae3420333)
![Imagem2](https://github.com/user-attachments/assets/08d4bb4d-fccc-4df8-82d7-34fb68deca6a)
![Imagem3](https://github.com/user-attachments/assets/0c507be6-505c-4df8-b947-be0331276d8e)
![Imagem4](https://github.com/user-attachments/assets/4d18fb48-d65d-4dc6-af81-71112b1a2e8a)
![Imagem5](https://github.com/user-attachments/assets/3e604630-d7f9-4090-8f89-2ceb4ed382fc)
![Imagem6](https://github.com/user-attachments/assets/cb49c2a6-688f-4880-9228-adbc3a91feae)
![Imagem7](https://github.com/user-attachments/assets/f96cd406-1fed-4837-9339-5289ac2a3157)
