### ISSUE TITLE
Criação e configuração do serviço do SonarQube no Jenkins

### ISSUE THREAD

**Issue by Ronynetwork** [Ronynetwork/AVSAC#3]
Nesta issue deverá ser feita toda a configuração inicial do serviço do SonarQube dentro do Jenkins, contendo a instalação dos Plugins, configuração de variaveis de ambiente e credenciais necessárias.

**Comment by 1Sayza** [comment]
Criação do arquivo do Docker compose do serviço do sonarqube 

version: '3.8'

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

**Comment by 1Sayza** [comment]
Estudando sobre o sonarqube utilizando a fonte da documentação da ferramente. Segue o link https://docs.sonarsource.com/sonarqube/latest/

**Comment by 1Sayza** [comment]
Mudei o arquivo do docker compose do sonarqube e subir o serviço novamente. Tinha criado a imagem errada. Segue em anexo em baixo o script estruturado. 

version: '3.8'

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonar-net

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    command: ["sh", "-c", "sleep 20 && sonar-scanner"]
    volumes:
      - ./test_scripts:/usr/src
    networks:
      - sonar-net

networks:
  sonar-net:

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

**Comment by 1Sayza** [comment]
Em acordo com a documentação do sonarqube, precisamos instalar o sonarscanner. Segue o link da documentação referente a essa tratativa https://docs.sonarsource.com/sonarqube/9.9/analyzing-source-code/scanners/sonarscanner/

**Comment by 1Sayza** [comment]
Docker Compose para iniciar o serviço do SonarQube, baixando a imagem diretamente do repositório oficial do Docker. A utilização do Docker Compose é essencial para configurar os volumes de armazenamento e definir as portas de comunicação. Isso facilita a gestão e a configuração do ambiente, garantindo que o SonarQube opere com as configurações necessárias para seu funcionamento adequado. Segue em anexo a evidência do script sendo executado. 

![Captura de tela de 2024-08-04 19-52-18](https://github.com/user-attachments/assets/11d78a26-26ec-435d-a8b2-aa6886f80ec1)

**Comment by 1Sayza** [comment]
![Captura de tela de 2024-08-06 20-57-46](https://github.com/user-attachments/assets/30ded014-9975-43fb-83e5-206a652b2c1b)

Serviço do sonarqube no ar!

**Comment by 1Sayza** [comment]
Para realizar a integração do sonarqube ao serviço do jenkins, que irá orquestrar a pipeline. Realizei o primeiro teste de conexão com o repositório do github. 

![jenkins](https://github.com/user-attachments/assets/4ba97096-1c3f-481f-9075-e88c2ebfbdbe)

**Comment by 1Sayza** [comment]
Integração do jenkins a build do docker do sonarqube, através da pipeline. 

![Captura de tela de 2024-08-08 00-17-03](https://github.com/user-attachments/assets/b41ac19f-9aa3-4d25-987c-01c46a6348e9)

**Comment by 1Sayza** [comment]
Os resultados verdes,  foram realizado com sucesso a integração.  Os teste anteriores que deram a mensagem em vermelho, estava verificando os logs, para ajustar no ambiente e na pipeline do arquivo. Como por exemplo, nomes de variáveis ou arquivos não encontrados.

**Comment by 1Sayza** [comment]
Integração do jenkins a build do docker do sonarqube, através da pipeline.

![WhatsApp Image 2024-08-08 at 11 11 15](https://github.com/user-attachments/assets/4fd620fb-644c-489b-aed5-937ee570281a)
