### ISSUE TITLE
Configuração do Quality Gates no SonarQube

### ISSUE THREAD

**Issue by Ronynetwork** [Ronynetwork/AVSAC#6]
Realizar a configuração dos requesitos para o sucesso da verificação do código dentro do dashboard do SonarQube.

**Comment by 1Sayza** [comment]
Importância do Quality Gate
Prevenção de problemas de qualidade: O Quality Gate ajuda a detectar problemas de qualidade no código logo nas fases iniciais do desenvolvimento, evitando que defeitos sejam propagados para o produto final.
Manutenção de padrões de qualidade: Ao definir critérios claros que o código deve atender, ele assegura que todos os desenvolvedores sigam os mesmos padrões de qualidade, resultando em um código mais coeso e sustentável.
Redução de custos a longo prazo: Identificar e corrigir problemas de código nas fases iniciais é menos custoso do que corrigi-los após o código ter sido implementado ou lançado.
Facilitação de auditorias e conformidade: O Quality Gate facilita a conformidade com padrões de qualidade e auditorias, fornecendo uma métrica clara sobre a saúde do código.

**Comment by 1Sayza** [comment]
Por padrão na ferramenta do Sonarqube, já vem várias políticas de Quality Gate configurada para cada linguagem e os níveis de critérios de segurança e qualidade aplicada no scan do código para verificação. Só que, como estamos elaborando o projeto para próxima sprint v4, a gente testar vários códigos. Nesse caso, precisei configurar uma manual de regra e selecionar os níveis de critérios que eu precisava e ir ajustando a medida que for analisando os códigos em acordo com a sprint v4. Então segue em anexo, logo abaixo, o print da política do Quality Gate, configurada por mim.

**Comment by 1Sayza** [comment]
![Screenshot_5](https://github.com/user-attachments/assets/9c04cb6a-1d1b-434d-8dc9-3db7bcb99ee2)
![Screenshot_6](https://github.com/user-attachments/assets/d2f02fba-359f-4065-937f-bcff82e5fa85)

**Comment by 1Sayza** [comment]
Nesse anexo logo abaixo, é o resultado da pipeline funcionando o estágio da análise do código, que foi implementado por Ronyldo na configuração da pipeline. 
![Uploading Screenshot_2.jpg…]()

**Comment by 1Sayza** [comment]
![Uploading Screenshot_3.jpg…]()

**Comment by 1Sayza** [comment]
![importante](https://github.com/user-attachments/assets/521e4d74-0163-4844-bb30-3d784a1359c2)

**Comment by 1Sayza** [comment]
Segue os resultados das configurações do Quality Gate do sonarqube. 

![projeto123](https://github.com/user-attachments/assets/b18d5c80-a805-4772-baf9-b6121c5d3cdd)
![Uploading projeto12345.png…]()

**Comment by 1Sayza** [comment]
Rodando novamente a pipeline com o estágio do Quality Gate. Temos o seguinte processo anexado logo abaixo.

![sonar](https://github.com/user-attachments/assets/f7463ceb-6276-4e2f-96f2-21d088b78b82)
