### ISSUE TITLE
Buscando códigos para realizar os testes da aplicação

### ISSUE THREAD

**Issue by Ronynetwork** [Ronynetwork/AVSAC#8]
Neste issue ambos colaboradores irão realizar a busca e inserção de códigos para testes das funcionalidades do SonarQube.

**Comment by 1Sayza** [comment]
Durante esta Sprint, entrei em contato com um amigo e solicitei a sua permissão para realizar um teste em um dos projetos que ele desenvolveu, um site de streaming de filmes. Durante a nossa conversa, rodei a  pipeline, para verificar a segurança do seu código desenvolvido, dentro das políticas do quality gate. Logo em seguida, observamos juntos os reportes acionados e trabalhamos para corrigir e verificar se a correção que o sonarqube informava, não iria quebrar a aplicação. Tudo ocorreu de forma esperada, realizamos a correção que a sonarqube alertou com falha de segurança e a aplicação subiu normalmente, sem nem uma falha. 

Segue o link do repositório https://github.com/redmarverick/MMDB 

Linguagens Scaneadas foram: Javascript e HTML.

**Comment by 1Sayza** [comment]
A ferramenta Sonarqube validou as políticas do Quality Gate e encontrou falhas no código relacionado a segurança! 


![WhatsApp Image 2024-08-19 at 00 18 20](https://github.com/user-attachments/assets/a3315d80-627d-45cf-a3b5-81725d679bd9)

**Comment by 1Sayza** [comment]
Segue as evidências das falhas encontradas:

![WhatsApp Image 2024-08-19 at 23 35 33](https://github.com/user-attachments/assets/3ac3efb8-194a-467e-aa3a-3f3d509360aa)

**Comment by 1Sayza** [comment]
O sonarqube orientou para realizar a seguinte correção, segue o script em abaixo:

<script src="https://cdnexample.com/script.js" integrity="sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"></script> 


![WhatsApp Image 2024-08-19 at 23 37 11](https://github.com/user-attachments/assets/86fe5f6a-97bf-4727-85c7-c9df040b414d)

**Comment by 1Sayza** [comment]
A segunda verificação que ele apontou como falha de segurança, segue o anexo abaixo:

![WhatsApp Image 2024-08-19 at 23 38 48](https://github.com/user-attachments/assets/8f337316-6881-46d7-922f-12f59432a2bf)

**Comment by 1Sayza** [comment]
A correção que o Sonar recomenda segue em anexo abaixo: 

Ele pede para ajustar a questão do html 

Compliant Solution
<!DOCTYPE html>
<html lang="en">
    <head>
          <title>A page written in english</title>
          <meta content="text/html; charset=utf-8" />
    </head>  


    <body>     
    ...   
    </body>
</html>
<!DOCTYPE html>
<html lang="en" xml:lang="en">
    <head>
          <title>A page written in english</title>
          <meta content="text/html; charset=utf-8" />
    </head>  


    <body>     
    ...   
    </body>
</html>

![WhatsApp Image 2024-08-19 at 23 39 09](https://github.com/user-attachments/assets/407ecd45-e36c-41fe-9c73-3c1b3aa29b23)

**Comment by 1Sayza** [comment]
Segue as seguintes correções realizada no arquivo index.html 

![WhatsApp Image 2024-08-20 at 11 24 56](https://github.com/user-attachments/assets/d094426e-88f3-4b95-9b71-03877cbb24c5)
![WhatsApp Image 2024-08-20 at 11 26 06](https://github.com/user-attachments/assets/7a559719-9523-486a-a213-02629d4f5f8a)

**Comment by 1Sayza** [comment]
Rodando novamente a construção da pipeline segue o resultado da validação do quality gate, depois do código corrigido. 

![WhatsApp Image 2024-08-19 at 23 30 13](https://github.com/user-attachments/assets/cdbfe1fc-0434-49b2-a138-9f85dd1b2847)
![WhatsApp Image 2024-08-19 at 23 32 43](https://github.com/user-attachments/assets/bc9adf13-5b22-45f5-af28-a08664cbfb49)

**Comment by 1Sayza** [comment]
Ferramenta sonarqube mostrando que se encontra validado o código! 

![WhatsApp Image 2024-08-19 at 00 52 18](https://github.com/user-attachments/assets/c3d17ede-7250-4b9a-9dd7-d86b84c123d8)

**Comment by 1Sayza** [comment]
Este anexo acabei esquecendo de anexar na etapas no início, mostrando como o sonarqube mostra as questões das vulnerabilidades do código de forma geral. 
![WhatsApp Image 2024-08-19 at 00 22 23](https://github.com/user-attachments/assets/fb78d59d-7b88-47df-b849-bb7269b87bff)

**Comment by 1Sayza** [comment]
Segue em anexo abaixo a aplicação no ar com as devidas correções. 

![WhatsApp Image 2024-08-20 at 15 43 18](https://github.com/user-attachments/assets/9bd74beb-f594-4a81-b944-ce101f4ba6aa)
